version: '2'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: postgres
